### ISSUE TITLE
side squares dissappearing on solve

### ISSUE THREAD

**Issue by denumerate** [merpig/RubiksProgram#1]
steps:
1) scrambled cube
2) set speed to faster
3) clicked solve

Seen behavior:
squares started to blink, at the end three were missing, the two on either side of the top corner and the one on the bottom of the right corner.

Expected behavior:
all them squares there

environment:
XPS 13 9350
Ubuntu 18.04.3
kernel 5.0.0-31.generic
Mozilla Firefox 70.0

**Comment by merpig** [comment]
Issue solved
